version: "3.7"
services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - 3000:3000
      - 35729:35729
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - REACT_APP_SERVER_PORT=${REACT_APP_SERVER_PORT:-3001}
    volumes:
      - './client/src:/app/src'
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 3001:3001
      - 9229:9229
    environment:
      - NODE_ENV=development
    volumes:
      - './server/src:/app/src'
